name: update
on:
  schedule:
    - cron: "0 3 * * 0" # Sunday 03:00 UTC
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          branch: automation/flake-update
          pr-title: "chore(flake): update flake inputs"
          pr-labels: dependencies
          pr-assignees: romaingrx

  build:
    needs: update-flake
    uses: ./.github/workflows/build.yml
    secrets: inherit
